language: java

env:
  global:
  - secure: PBZJXVCVnSLEVFYKymkIC+Eqkj6CD1/n+/odJwgM3wSg08FnTXc83KW+dxp1ot6sI47ZdCpBD0zOzAYf7/A1dUVng8FLNwNV/OXmIuU4u6E49rOAVlxANnF7hrdrAkFunQJFf8CGKdeWFiKtfUViluedsxcwM5F6l4FZamJyeLd/vohYdwZtBKwR186d61OX1eyJ7kOJKzKsY+sfJP8OlUzRovrqVXCr9VOaX4hkC98STWbmhql5eNKSufuZJuJHE72OlWZM/qGET1Y/RGfr7RNYBytx2+iCHcXHbc2oK6XyPE1zHtn1zl9a1/QvmYeDxihq+W5tsUvGf4qauAAZsLS8TFT/ZU4XlziCVHjHfcIlIHbUUKMLUYNzGP6xDYCyGJBud57FNhPdXm9YnEN6pobUiPcuPxec1YUZIwh4kSjDxxdd5S/utnyfwqFYiCMcBfjDCzlFj7gjZ5wUJYnKvYAQcMJ6INnshqjkaae+UJW4APxavQxyMv+1XJi+4Nz69r6gygp4cLXMVpMWOIfye3U0DRhht/MR+byZjmQWuR3wLolpIFhVU+DCHAY3uJ/evUhLOmJoFgK/VMKmXuerIWG8+2tYKfL+QSVAenXEA7OYQkmYbuVW8g8YJcuc3ddZIjo+woN7ZIRIEqUlhSi9emSqXIqA+zA7qdXMZbwBH9s=

after_success: bash .utility/update-gh-pages.sh
